import xml.etree.ElementTree as et
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import ElementTree

def createJob(
JOBISN="0",
APPLICATION="applicationName",
SUB_APPLICATION="subApplicationName",
#MEMNAME="BIHCK_P_EWPSGL_APRA_RS_LEDABD_CP", same as JOBNAME
JOBNAME="jobName",
DESCRIPTION="description",
CREATED_BY="majia",
RUN_AS="dsadm",
CRITICAL="0",
TASKTYPE="Command",
CYCLIC="0",
NODEID="hostName",
INTERVAL="00001M",
CMDLINE="",
CONFIRM="0",
DAYSCAL="CalenderName",
RETRO="0",
MAXWAIT="0",
MAXRERUN="0",
AUTOARCH="0",
MAXDAYS="0",
MAXRUNS="0",
DAYS="",
JAN="1",
FEB="1",
MAR="1",
APR="1",
MAY="1",
JUN="1",
JUL="1",
AUG="1",
SEP="1",
OCT="1",
NOV="1",
DEC="1",
DAYS_AND_OR="A",
SHIFT="Ignore Job",
SHIFTNUM="+00",
SYSDB="0",
IND_CYCLIC="S",
CREATION_USER="majia",
CREATION_DATE="00000000",#yyyymmdd
CREATION_TIME="000000",#hhmmss
CHANGE_USERID="majia",
CHANGE_DATE="00000000",#yyyymmdd
CHANGE_TIME="000000",#hhmmss
RULE_BASED_CALENDAR_RELATIONSHIP="O",
APPL_TYPE="OS",
MULTY_AGENT="N",
USE_INSTREAM_JCL="N",
VERSION_OPCODE="N",
IS_CURRENT_VERSION="Y",
VERSION_SERIAL="5",
VERSION_HOST="VPCAUTMHW71156",
CYCLIC_TOLERANCE="0",
CYCLIC_TYPE="C",
PARENT_FOLDER="folderName"
    ):
    job = Element('JOB', JOBISN=JOBISN, APPLICATION=APPLICATION, SUB_APPLICATION=SUB_APPLICATION, MEMNAME=JOBNAME, JOBNAME=JOBNAME, DESCRIPTION=DESCRIPTION, CREATED_BY=CREATED_BY, RUN_AS=RUN_AS, CRITICAL=CRITICAL, TASKTYPE=TASKTYPE, CYCLIC=CYCLIC, NODEID=NODEID, INTERVAL=INTERVAL, CMDLINE=CMDLINE, CONFIRM=CONFIRM, DAYSCAL=DAYSCAL, RETRO=RETRO, MAXWAIT=MAXWAIT, MAXRERUN=MAXRERUN, AUTOARCH=AUTOARCH, MAXDAYS=MAXDAYS, MAXRUNS=MAXRUNS, DAYS=DAYS, JAN=JAN, FEB=FEB, MAR=MAR, APR=APR, MAY=MAY, JUN=JUN, JUL=JUL, AUG=AUG, SEP=SEP, OCT=OCT, NOV=NOV, DEC=DEC, DAYS_AND_OR=DAYS_AND_OR, SHIFT=SHIFT, SHIFTNUM=SHIFTNUM, SYSDB=SYSDB, IND_CYCLIC=IND_CYCLIC, CREATION_USER=CREATION_USER, CREATION_DATE=CREATION_DATE, CREATION_TIME=CREATION_TIME, CHANGE_USERID=CHANGE_USERID, CHANGE_DATE=CHANGE_DATE, CHANGE_TIME=CHANGE_TIME, RULE_BASED_CALENDAR_RELATIONSHIP=RULE_BASED_CALENDAR_RELATIONSHIP, APPL_TYPE=APPL_TYPE, MULTY_AGENT=MULTY_AGENT, USE_INSTREAM_JCL=USE_INSTREAM_JCL, VERSION_OPCODE=VERSION_OPCODE, IS_CURRENT_VERSION=IS_CURRENT_VERSION, VERSION_SERIAL=VERSION_SERIAL, VERSION_HOST=VERSION_HOST, CYCLIC_TOLERANCE=CYCLIC_TOLERANCE, CYCLIC_TYPE=CYCLIC_TYPE, PARENT_FOLDER=PARENT_FOLDER)
    tree = ElementTree(job)
    job.text=" "
    #childJob = Element('INCONDITION')
    #job.append(childJob)
    #print(et.tostring(job))
    
createJob(JOBNAME="modjobName",APPLICATION="modapplicationName")
