AR = [
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHSYPMT05 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTSYPMT05 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSSYPMT05 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPCSYPMT05 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTSYPM144 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSSYPM073 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHSYPM073 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTRWPM019 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTPSPM002 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHDLPT011 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTDLPM239 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSDLPM239 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHDLPM239 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTDLPM238 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSDLPM238 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHDLPM238 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTBUPT045 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHBUPT045 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPCBUPT045 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTBUPM106 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSBUPM106 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHBUPM106 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTBUPM049 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTBUPM023 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPCBUPM001 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTACPT161 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSACPT161 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHACPT161 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPCACPT161 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTACPM038 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTACPM007 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPTACPE012 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPSACPE012 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPHACPE012 JP Y N N %%$ODATE',
'/opt/ibm/working/BIH_T2/appl/sh/Sinfile_Arch.sh BIHDM02T MIDANZ_JP_JPCACPE012 JP Y N N %%$ODATE',
]
FW = [
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHSYPMT05_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTSYPMT05_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSSYPMT05_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPCSYPMT05_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTSYPM144_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSSYPM073_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHSYPM073_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTRWPM019_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTPSPM002_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHDLPT011_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTDLPM239_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSDLPM239_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHDLPM239_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTDLPM238_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSDLPM238_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHDLPM238_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTBUPT045_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHBUPT045_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPCBUPT045_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTBUPM106_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSBUPM106_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHBUPM106_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTBUPM049_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTBUPM023_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPCBUPM001_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTACPT161_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSACPT161_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHACPT161_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPCACPT161_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTACPM038_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTACPM007_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPTACPE012_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPSACPE012_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPHACPE012_??????????????.tag',
'ctmfw "/opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new/MIDANZ_JP_JPCACPE012_??????????????.tag'
]
DLT = [
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPCSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTSYPM144_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSSYPM073_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHSYPM073_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTRWPM019_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTPSPM002_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHDLPT011_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPCBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTBUPM049_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTBUPM023_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPCBUPM001_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPCACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTACPM038_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTACPM007_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPTACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPSACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPHACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_P/appl/sh/Fileremove.sh MIDANZ_JP_JPCACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/RSDS'
]
CP = [
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPCSYPMT05_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTSYPM144_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSSYPM073_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHSYPM073_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTRWPM019_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTPSPM002_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHDLPT011_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHDLPM239_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHDLPM238_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPCBUPT045_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHBUPM106_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTBUPM049_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTBUPM023_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPCBUPM001_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPCACPT161_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTACPM038_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTACPM007_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPTACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPSACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPHACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS',
'/opt/ibm/working/BIH_T2/appl/sh/EDW/File_Copy_V2.sh MIDANZ_JP_JPCACPE012_??????????????.* /opt/ibm/working/BIH_ICR_P/data/in/MIDANZ/JP/new /opt/ibm/working//BIH_ICR_P/data/in/MIDANZ/JP/RSDS'
]
RG = [
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHSYPMT05 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHSYPMT05" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTSYPMT05 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTSYPMT05" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSSYPMT05 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSSYPMT05" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPCSYPMT05 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPCSYPMT05" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTSYPM144 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTSYPM144" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSSYPM073 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSSYPM073" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHSYPM073 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHSYPM073" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTRWPM019 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTRWPM019" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTPSPM002 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTPSPM002" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHDLPT011 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHDLPT011" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTDLPM239 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTDLPM239" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSDLPM239 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSDLPM239" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHDLPM239 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHDLPM239" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTDLPM238 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTDLPM238" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSDLPM238 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSDLPM238" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHDLPM238 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHDLPM238" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTBUPT045 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTBUPT045" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHBUPT045 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHBUPT045" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPCBUPT045 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPCBUPT045" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTBUPM106 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTBUPM106" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSBUPM106 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSBUPM106" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHBUPM106 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHBUPM106" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTBUPM049 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTBUPM049" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTBUPM023 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTBUPM023" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPCBUPM001 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPCBUPM001" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTACPT161 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTACPT161" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSACPT161 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSACPT161" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHACPT161 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHACPT161" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPCACPT161 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPCACPT161" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTACPM038 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTACPM038" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTACPM007 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTACPM007" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPTACPE012 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPTACPE012" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPSACPE012 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPSACPE012" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPHACPE012 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPHACPE012" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j BIH_File_Reg_ZRC_ASCII.MID_JPCACPE012 -v "PS_GENERIC=RSDS_BIH_MIDANZJP_EPS" -v "PS_RSDS2=MIDANZJP_JPCACPE012" -v "PS_ACE_BIH=RSDS_BIH_MIDANZ_JP"'
]
LD = [
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHSYPMT05 -v "PS_RSDS2=MIDANZJP_JPHSYPMT05" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHSYPMT05" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTSYPMT05 -v "PS_RSDS2=MIDANZJP_JPTSYPMT05" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTSYPMT05" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSSYPMT05 -v "PS_RSDS2=MIDANZJP_JPSSYPMT05" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSSYPMT05" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPCSYPMT05 -v "PS_RSDS2=MIDANZJP_JPCSYPMT05" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPCSYPMT05" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTSYPM144 -v "PS_RSDS2=MIDANZJP_JPTSYPM144" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTSYPM144" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSSYPM073 -v "PS_RSDS2=MIDANZJP_JPSSYPM073" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSSYPM073" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHSYPM073 -v "PS_RSDS2=MIDANZJP_JPHSYPM073" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHSYPM073" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTRWPM019 -v "PS_RSDS2=MIDANZJP_JPTRWPM019" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTRWPM019" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTPSPM002 -v "PS_RSDS2=MIDANZJP_JPTPSPM002" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTPSPM002" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHDLPT011 -v "PS_RSDS2=MIDANZJP_JPHDLPT011" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHDLPT011" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHDLPM239 -v "PS_RSDS2=MIDANZJP_JPHDLPM239" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHDLPM239" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSDLPM239 -v "PS_RSDS2=MIDANZJP_JPSDLPM239" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSDLPM239" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHDLPM239 -v "PS_RSDS2=MIDANZJP_JPHDLPM239" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHDLPM239" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTDLPM238 -v "PS_RSDS2=MIDANZJP_JPTDLPM238" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTDLPM238" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSDLPM238 -v "PS_RSDS2=MIDANZJP_JPSDLPM238" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSDLPM238" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHDLPM238 -v "PS_RSDS2=MIDANZJP_JPHDLPM238" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHDLPM238" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTBUPT045 -v "PS_RSDS2=MIDANZJP_JPTBUPT045" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTBUPT045" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHBUPT045 -v "PS_RSDS2=MIDANZJP_JPHBUPT045" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHBUPT045" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPCBUPT045 -v "PS_RSDS2=MIDANZJP_JPCBUPT045" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPCBUPT045" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTBUPM106 -v "PS_RSDS2=MIDANZJP_JPTBUPM106" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTBUPM106" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSBUPM106 -v "PS_RSDS2=MIDANZJP_JPSBUPM106" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSBUPM106" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHBUPM106 -v "PS_RSDS2=MIDANZJP_JPHBUPM106" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHBUPM106" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTBUPM049 -v "PS_RSDS2=MIDANZJP_JPTBUPM049" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTBUPM049" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTBUPM023 -v "PS_RSDS2=MIDANZJP_JPTBUPM023" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTBUPM023" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPCBUPM001 -v "PS_RSDS2=MIDANZJP_JPCBUPM001" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPCBUPM001" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTACPT161 -v "PS_RSDS2=MIDANZJP_JPTACPT161" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTACPT161" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSACPT161 -v "PS_RSDS2=MIDANZJP_JPSACPT161" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSACPT161" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHACPT161 -v "PS_RSDS2=MIDANZJP_JPHACPT161" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHACPT161" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPCACPT161 -v "PS_RSDS2=MIDANZJP_JPCACPT161" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPCACPT161" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTACPM038 -v "PS_RSDS2=MIDANZJP_JPTACPM038" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTACPM038" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTACPM007 -v "PS_RSDS2=MIDANZJP_JPTACPM007" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTACPM007" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPTACPE012 -v "PS_RSDS2=MIDANZJP_JPTACPE012" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPTACPE012" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPSACPE012 -v "PS_RSDS2=MIDANZJP_JPSACPE012" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPSACPE012" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPHACPE012 -v "PS_RSDS2=MIDANZJP_JPHACPE012" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPHACPE012" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"',
'/opt/ibm/working/BIH_P/appl/sh/EDW/RunDataStageJob.ksh -p BIH_RSDS_APRA2_P -r -j SRC_to_RSDS_Seq2.MID_JPCACPE012 -v "PS_RSDS2=MIDANZJP_JPCACPE012" -v "PS_COUNTRY_CALENDAR=MIDANZJP_JPCACPE012" -v "PS_SHARED_PARAMETERS=PS_SHARED_PARAMETERS_VW" -v "PS_CNTRL_FWORK=PS_CNTRL_FWORK_MIDANZJP_EPS"'
]
TV = [
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPCACPE012 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHACPE012 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSACPE012 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTACPE012 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTACPM007 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTACPM038 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPCACPT161 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHACPT161 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSACPT161 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTACPT161 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPCBUPM001 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTBUPM023 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTBUPM049 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHBUPM106 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSBUPM106 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTBUPM106 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPCBUPT045 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHBUPT045 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTBUPT045 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHDLPM238 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSDLPM238 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTDLPM238 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHDLPM239 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSDLPM239 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTDLPM239 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHDLPT011 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTPSPM002 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTRWPM019 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHSYPM073 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSSYPM073 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTSYPM144 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPCSYPMT05 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPHSYPMT05 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPSSYPMT05 -d %%ORDATE',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/TREND_CHK.ksh -t MIDANZ_JPTSYPMT05 -d %%ORDATE'
]
DV = [
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPCACPE012',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHACPE012',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSACPE012',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTACPE012',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTACPM007',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTACPM038',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPCACPT161',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHACPT161',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSACPT161',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTACPT161',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPCBUPM001',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTBUPM023',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTBUPM049',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHBUPM106',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSBUPM106',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTBUPM106',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPCBUPT045',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHBUPT045',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTBUPT045',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHDLPM238',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSDLPM238',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTDLPM238',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHDLPM239',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSDLPM239',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTDLPM239',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHDLPT011',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTPSPM002',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTRWPM019',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHSYPM073',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSSYPM073',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTSYPM144',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPCSYPMT05',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPHSYPMT05',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPSSYPMT05',
'ksh /opt/ibm/working/BIH_P/POST_VALIDATION/DUPLICATE_CHK_Bteq_Daily.ksh -t MIDANZ_JPTSYPMT05'
]